builds:
  - id: jwtpxy
    main: ./cmd/jwtpxy.go
    binary: jwtpxy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
      - -a
      - -v
    ldflags: -s -w -X main.Version={{.Version}}

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/txn2/jwtpxy
    description: JWT reverse proxy.
    maintainer: Craig Johnston https://twitter.com/cjimti
    license: MIT
    vendor: https://github.com/txn2
    formats:
      - apk
      - deb
      - rpm
    recommends:
      - kubectl

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: txn2
    name: jwtpxy

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: false

  # You can change the name of the GitHub release.
  # Default is ``
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    image_templates:
      - "txn2/jwtpxy:latest"
      - "txn2/jwtpxy:{{ .Tag }}"
      - "txn2/jwtpxy:{{ .Major }}"
      - "txn2/jwtpxy:amd64-{{ .Tag }}"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
